apiVersion: v1
kind: Service
metadata:
  name: kurt
  labels:
    app: kurt
spec:
  ports:
  - port: 444
    targetPort: 80
  type: NodePort
  selector:
    app: kurt
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: kurt
  labels:
    app: kurt
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kurt
    spec:
      containers:
      - name: kurt
        image: nginx
        ports:
        - containerPort: 80
